sudo: required
dist: trusty
language: cpp
addons:
  chrome: stable

matrix:
  include:
    - os: linux
      compiler: gcc

before_install:
  - sudo apt-get update && sudo apt-get install build-essential software-properties-common -y && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-snapshot -y
  - sudo apt-get install gcc-6 g++-6 -y
  - sudo apt-get install cppcheck
  - sudo apt-get install valgrind
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - curl https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr
  - sudo apt-get install libboost-all-dev
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - sudo npm i -g npm

install:
  - echo `which $CC`
  - echo `which $CXX`
  - node -v
  - npm -v
  - pwd
  - cd templates
  - yarn install
  - ls .
  - ls **/*
  - cd ..

script:
  - echo `which $CXX`
  - pwd
  - cd templates
  - yarn test
  - cd ..
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX ..
  - make server
  

notifications:
  email: false
